In [2]:
import numpy as np

#identity matrix can be created using 2 functions
#EYE()--> USED TTO DEFINE both user defined rows and coloumns
#identity()-->used to define same number of rows and coloumns

#syntax-->np.identity(5)-->5 is 5 rows and 5 coloumns
#syntax-->np.eye(3,4)--> 3 rows and 4 coloumns


np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [35]:
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
np.identity(5, dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [13]:
ar1=np.arange(13)

In [14]:
ar1
len(ar1)

13

In [15]:
reshaped_array=ar1.reshape(13,1)

In [16]:
reshaped_array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [17]:
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
#To perform multidimensional slicing
ar2=np.arange(25).reshape(5,5)
#ar2[rows,coloumns,step]
#ar2[row_start:row_end,col_start,col_end,step]
ar2[0:3,1:4]



array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [23]:
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ar2.shape

(5, 5)

In [25]:
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:

ar2[0:3,1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [28]:
ar2[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
ar2[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [32]:
ar2[-1:-4,1:3]

array([], shape=(0, 2), dtype=int32)

In [33]:
ar2[1:-2]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
ar2[3:4,-2]

array([18])

In [36]:
ar2[-4:4]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
ar2[-4:-2,]

array([ 7, 12])

In [40]:
ar2[-4:-2,-3]


array([ 7, 12])

In [41]:
ar2[-4:-2,-4:-2]

array([[ 6,  7],
       [11, 12]])

In [43]:
#print
#print
#print



ar3=np.arange(50).reshape(5,10)
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [48]:
#linspace()


np.sum(ar3,axis=0)# to add based on coloumns wise axis=0
np.sum(ar3,axis=0)# to add based on rows wise axis=1


array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [46]:
np.sum(ar3,axis=0)# to add based on coloumns wise axis=0

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [47]:
np.sum(ar3)

1225

In [ ]:
mean-->average
median-->center value
mode-->max num of repeated element
variance-->medain/total num of elements
std--> square root of varaince

In [49]:
#linspace()
np.linspace(1,5)


array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [50]:
#linspace()
np.linspace(10,5)

array([10.        ,  9.89795918,  9.79591837,  9.69387755,  9.59183673,
        9.48979592,  9.3877551 ,  9.28571429,  9.18367347,  9.08163265,
        8.97959184,  8.87755102,  8.7755102 ,  8.67346939,  8.57142857,
        8.46938776,  8.36734694,  8.26530612,  8.16326531,  8.06122449,
        7.95918367,  7.85714286,  7.75510204,  7.65306122,  7.55102041,
        7.44897959,  7.34693878,  7.24489796,  7.14285714,  7.04081633,
        6.93877551,  6.83673469,  6.73469388,  6.63265306,  6.53061224,
        6.42857143,  6.32653061,  6.2244898 ,  6.12244898,  6.02040816,
        5.91836735,  5.81632653,  5.71428571,  5.6122449 ,  5.51020408,
        5.40816327,  5.30612245,  5.20408163,  5.10204082,  5.        ])

In [51]:
#linspace()
#it is used to print th  eventy seperated pointed
#b/w 2 range of values
np.linspace(1,10,4,dtype=int)#-->linspace(strut,end,num of values)

array([ 1.,  4.,  7., 10.])

In [52]:
np.linspace(12,30,12,retstep=True)

(array([12.        , 13.63636364, 15.27272727, 16.90909091, 18.54545455,
        20.18181818, 21.81818182, 23.45454545, 25.09090909, 26.72727273,
        28.36363636, 30.        ]),
 1.6363636363636365)

In [56]:
#random module
#to generate random number between the range

#np.random.randint(start,end, num_of_values)
#np.random.randint(40)
#or
np.random.randint(20,30)

20

In [58]:
np.random.randint(30,40,3)

array([39, 33, 38])

In [62]:
#rand()-->
#to get the randomly generated values from 0 to 1,based on
#uniform distribution

np.random.rand(10)

array([0.47623116, 0.54043179, 0.87146877, 0.95097829, 0.64014713,
       0.43839227, 0.74453992, 0.96625965, 0.66571141, 0.10657694])

In [66]:
#rand()-->
#to get the randomly generated values from 0 to 1,based on
#normal distribution

np.random.randn(5,4)

array([[-1.19002006, -0.57726987, -0.00374348,  0.84895273],
       [-0.13326033, -2.37185021, -0.37397185,  0.29584675],
       [ 0.44292277, -0.75872948,  0.09706727,  0.53409459],
       [ 1.65711304,  0.51777809, -0.25311058,  1.46528941],
       [-0.34511595,  0.23222551, -0.16137507,  0.18336333]])

In [71]:
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [67]:
ar3.min()

0

In [68]:
ar3.max()

49

In [69]:
#to find the index of min values
l1=[56,89,90,67,45]
np1=np.array(l1)
print(l1.index(67))

3


In [70]:
print(ar3.tolist())

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29], [30, 31, 32, 33, 34, 35, 36, 37, 38, 39], [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]


In [74]:
l1=[56,89,90,67,45]
np1=np.array(l1)
#argmin()--> to find the min values index position in an array
print(np1.argmin()) 
#argmax()-->to find the max values index position in an array
print(np1.argmax())

4
2


In [75]:
np1


array([56, 89, 90, 67, 45])

In [76]:
np.sin(np1)

array([-0.521551  ,  0.86006941,  0.89399666, -0.85551998,  0.85090352])

In [77]:
np.cos(np1)
np.tan(np1)

array([-0.61127369,  1.68582537, -1.99520041,  1.65231726,  1.61977519])

In [78]:
1/np.sin(np1)

array([-1.91735803,  1.16269686,  1.11857241, -1.16887977,  1.17522136])

In [79]:
np.cos(np1)+np.sin(np1)

array([ 0.33166911,  1.37024645,  0.44592305, -1.37328978,  1.37622551])

In [80]:
np.cos(np1)/np.sin(np1)

array([-1.63592842,  0.59318125, -0.50120278,  0.60521065,  0.61736962])

In [84]:
#Task:1--> write python code for the below logic
np2=np.array([1,2,3])
np3=np.array([4,5,6])
#(1*4)+(2*5)+(3*6)=4+10+18-->32
a1=np2[0]*np3[0]
a2=np2[1]*np3[1]
a3=np2[2]*np3[2]
print(a1+a2+a3)

32


In [91]:
np2=np.array([1,2,3,9])
np3=np.array([4,5,6,0])
#(1*4)+(2*5)+(3*6)=4+10+18-->32
a1=np2[0]*np3[0]
a2=np2[1]*np3[1]
a3=np2[2]*np3[2]
a4=np2[3]*1
print(a1+a2+a3+a4)
print(np2*np3)

41
[ 4 10 18  0]


In [118]:
np2=np.array([1,2,3])
np3=np.array([4,5,6])
#(1*4)+(2*5)+(3*6)=4+10+18-->32
#np2*np3


fname=np.array(["sid","fn1","fn2"])
lname=np.array(["T","ln1","ln2"])
# fname.tostring()
fname
lname
#string concatenation
print(np.append(fname,lname))

['sid' 'fn1' 'fn2' 'T' 'ln1' 'ln2']


In [105]:
lname

array(['T', 'ln1', 'ln2'], dtype='<U3')

In [110]:
len1=len(np2)

3

In [111]:
len2=len(np3)

3

In [119]:
np2=np.array([1,2,3])
np3=np.array([4,5,6])

len1=len(np2)
len2=len(np3)

diff=abs(len1-len2)
for val in range(diff):
    np3=np.append(np3,1)
    
np.sum((np2*np3))
    

32

In [121]:
np1=np.array([1,34,56,78,np.nan,np.nan])

In [122]:
#To print nan values
np1[np.isnan(np1)]

array([nan, nan])

In [123]:
#to elminate nan values
np1[~np.isnan(np1)]

array([ 1., 34., 56., 78.])

In [125]:
#to print multiplitaction of corresponding index values and add all producted values
np2=np.array([1,2,3])
np3=np.array([4,5,6])
np.dot(np2,np3)


32

In [127]:
#pandas module
import pandas as pd
#pandas is defines as an open-source library that provides
#high performance data manpulation in python.
#data analysis requires lot of processing such as restructuring,
#cleaning,mergin,manipulatingetc... we prefer pandas to 
#perform the 
#above functionalities coz it is fast,simple than other tools.

#panda is built on numpy,numpy is required for operating 
#pandas

In [128]:
#panda series
#pandas series is a data structure with one dimensional labelled array
#it is a primary building block of dataframe,making its rows and columns

In [137]:
labels=['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={'a':100, "b":200, "c":300}

In [136]:
#syntax-->pandas.Series(data=None, index=None, dtype=None, name=None,copy=True or False)

#Eg:1
import pandas as pd
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [138]:
type(pd.Series(my_data))

pandas.core.series.Series

In [139]:
#Series with labels
pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [142]:
#Series with labels
#pd.Series(data=my_data,index=labels)
#or
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [141]:
pd.Series(data=[print(),len,sum])

0                       None
1    <built-in function len>
2    <built-in function sum>
dtype: object

In [144]:
class profile:
    def display():
        print("my name is mag")

p=profile
p.display()

my name is mag


In [145]:
class profile:
    @property
    def display(self):
        print("my name is mag")

p=profile()
p.display

my name is mag


In [148]:
#class profile:
#     @property
#    def display(self):
#        print("my name is mag")
#
#p=profile()
#p.display

def decor(func):
    def inner():
        str1=func()
        return str1.upper()
    return inner()
       
def greet():
    return "good morning"
print(greet())
    

good morning


In [150]:
def decor(func):
    def inner():
        str1=func()
        return str1.upper()
    return inner()
       
def greet():
    return "good morning"
print(decor(greet))
    

GOOD MORNING


In [151]:
#def decor(func):
# def inner():
# str1=func()
# return str1.upper()
# return inner()
#@decor     
#def greet():
#    return "good morning"
#print(greet())
 
ser1=pd.Series([1,2,3,4,5],['USA',"India","Canada","UK","Egypt"])

In [152]:
ser1

USA       1
India     2
Canada    3
UK        4
Egypt     5
dtype: int64

In [153]:
ser1['USA']

1

In [154]:
#access values using indexing
ser1[0:3]

USA       1
India     2
Canada    3
dtype: int64

In [156]:
ser2=pd.Series([5,6,7,8],['USA','Brazil',"Canada","UK"])

In [157]:
ser1+ser2

Brazil     NaN
Canada    10.0
Egypt      NaN
India      NaN
UK        12.0
USA        6.0
dtype: float64

In [158]:
ser1-ser2

Brazil    NaN
Canada   -4.0
Egypt     NaN
India     NaN
UK       -4.0
USA      -4.0
dtype: float64

In [159]:
#To create a new data in series
ser2


USA       5
Brazil    6
Canada    7
UK        8
dtype: int64

In [160]:
ser2['china']="duplicate"

In [161]:
ser2

USA               5
Brazil            6
Canada            7
UK                8
china     duplicate
dtype: object

In [162]:
ser2.drop('USA')

Brazil            6
Canada            7
UK                8
china     duplicate
dtype: object

In [163]:
#DataFrame
#pd.DataFrame(datas,row_label,col_label)

In [165]:
df=pd.DataFrame(np.random.randn(5,4))

In [197]:
df

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [200]:
df=pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [189]:
df

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [174]:
#to convert dictionary to DataFrame
d={"col1":[1,2],"col2":[3,4],"col3":[5,6]}

In [175]:
d

{'col1': [1, 2], 'col2': [3, 4], 'col3': [5, 6]}

In [176]:
df=pd.DataFrame(data=d)

In [177]:
df

col1  col2  col3
0     1     3     5
1     2     4     6

In [178]:
df=pd.DataFrame(d,["row1","row2"])

In [179]:
df

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [180]:
df.index#syntax-->> get all the row name

Index(['row1', 'row2'], dtype='object')

In [181]:
df

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [183]:
df

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [184]:
df.T

row1  row2
col1     1     2
col2     3     4
col3     5     6

In [185]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [186]:
type(df)

pandas.core.frame.DataFrame

In [187]:
df.dtypes

col1    int64
col2    int64
col3    int64
dtype: object

In [188]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, row1 to row2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    2 non-null      int64
 1   col2    2 non-null      int64
 2   col3    2 non-null      int64
dtypes: int64(3)
memory usage: 172.0+ bytes


In [190]:
df.values

array([[1, 3, 5],
       [2, 4, 6]], dtype=int64)

In [191]:
df.axes

[Index(['row1', 'row2'], dtype='object'),
 Index(['col1', 'col2', 'col3'], dtype='object')]

In [192]:
df.ndim

2

In [193]:
df.size

6

In [201]:
df

W         X         Y         Z
A -3.041947  0.309321  0.605304 -0.755289
B  0.344300  0.879813 -0.025546 -0.231851
C  0.870220 -0.150307  0.834612 -0.818802
D  0.107928 -1.214375  0.185224 -0.429324
E -1.076024  0.417467 -0.966715  0.437613

In [204]:
df

W         X         Y         Z
A -3.041947  0.309321  0.605304 -0.755289
B  0.344300  0.879813 -0.025546 -0.231851
C  0.870220 -0.150307  0.834612 -0.818802
D  0.107928 -1.214375  0.185224 -0.429324
E -1.076024  0.417467 -0.966715  0.437613

In [205]:
df['W']

A   -3.041947
B    0.344300
C    0.870220
D    0.107928
E   -1.076024
Name: W, dtype: float64

In [206]:
type(df['W'])

pandas.core.series.Series

In [213]:
df[['W','X','Y']]

W         X         Y
A -3.041947  0.309321  0.605304
B  0.344300  0.879813 -0.025546
C  0.870220 -0.150307  0.834612
D  0.107928 -1.214375  0.185224
E -1.076024  0.417467 -0.966715

In [217]:
#to create new columns
df['new']=df['W']+df['Y']

In [208]:
df

W         X         Y         Z       new
A -3.041947  0.309321  0.605304 -0.755289 -2.436643
B  0.344300  0.879813 -0.025546 -0.231851  0.318754
C  0.870220 -0.150307  0.834612 -0.818802  1.704832
D  0.107928 -1.214375  0.185224 -0.429324  0.293152
E -1.076024  0.417467 -0.966715  0.437613 -2.042739

In [218]:
df.drop('new',axis=1)

W         X         Y         Z
A -3.041947  0.309321  0.605304 -0.755289
B  0.344300  0.879813 -0.025546 -0.231851
C  0.870220 -0.150307  0.834612 -0.818802
D  0.107928 -1.214375  0.185224 -0.429324
E -1.076024  0.417467 -0.966715  0.437613

In [219]:
df

W         X         Y         Z       new
A -3.041947  0.309321  0.605304 -0.755289 -2.436643
B  0.344300  0.879813 -0.025546 -0.231851  0.318754
C  0.870220 -0.150307  0.834612 -0.818802  1.704832
D  0.107928 -1.214375  0.185224 -0.429324  0.293152
E -1.076024  0.417467 -0.966715  0.437613 -2.042739

In [214]:
df.drop('new',axis=1,inplace=True)

In [215]:
df

W         X         Y         Z
A -3.041947  0.309321  0.605304 -0.755289
B  0.344300  0.879813 -0.025546 -0.231851
C  0.870220 -0.150307  0.834612 -0.818802
D  0.107928 -1.214375  0.185224 -0.429324
E -1.076024  0.417467 -0.966715  0.437613